#!/usr/bin/env bash


if [ ! $(which node) ]; then
    echo 'Please install nodejs package'
    sudo apt install nodejs
#    exit 1
fi

if [ ! $(which npm) ]; then
    echo 'Please install npm package'
    sudo apt install npm
#    exit 1
fi

if (( $EUID != 0 )); then
    echo "Please run as root"
#    exit 1
fi


cp kdevice-gabbler.service /lib/systemd/system/

mkdir /opt/kdevice-gabbler 
cp -r kdevice-gabbler.js /opt/kdevice-gabbler/kdevice-gabbler.js
cp -r package.json /opt/kdevice-gabbler/package.json
cd /opt/kdevice-gabbler
npm install 



systemctl enable kdevice-gabbler.service
systemctl start kdevice-gabbler.service


echo "Done installing kdevice-gabbler"
exit 0